/**
 * Datos del bingo (orígenes y principios de Stellaris).
 *
 * Cada casilla es un objeto:
 *   { img: "origins/GFX_origin_default.png", i18nKey: "originXxx" }
 * - "img" es la ruta a la imagen dentro de la API de assets de Stellaris
 *   (https://morteux.github.io/StellarisAssets/), relativa a IMAGE_BASE.
 * - "i18nKey" es la clave de texto que se busca en los tres bloques de
 *   idioma (es/en/jp) dentro de js/i18n.js. Debe existir en los tres.
 *
 * ── Origen de las imágenes ─────────────────────────────────────────────
 * Las imágenes del bingo se sirven siempre desde la API de assets
 * (https://morteux.github.io/StellarisAssets/), nunca en local. Si esa URL
 * base cambia, edita únicamente STELLARIS_ASSETS_BASE en
 * js/asset-config.js: no hace falta tocar nada en este archivo.
 */
import { STELLARIS_ASSETS_BASE } from "./asset-config.js";

/**
 * IMAGE_BASE reexporta STELLARIS_ASSETS_BASE (definido en
 * js/asset-config.js): las imágenes del bingo se sirven siempre desde la
 * API de assets de Stellaris, nunca en local. Para cambiar de dónde se
 * sirven, edita STELLARIS_ASSETS_BASE en js/asset-config.js — no hace
 * falta tocar nada en este archivo.
 */
export const IMAGE_BASE = STELLARIS_ASSETS_BASE;

/** Bingo de orígenes. */
export const ORIGIN_BINGO = [
  { img: "origins/GFX_origin_default.png", i18nKey: "originDefault" },
  { img: "origins/GFX_origin_nomad_default.png", i18nKey: "originNomadDefault" },
  { img: "origins/GFX_origin_sacred_path.png", i18nKey: "originSacredPath" },
  { img: "origins/GFX_origin_heirs_of_the_khan.png", i18nKey: "originHeirsOfTheKhan" },
  { img: "origins/GFX_origin_forever_cruise.png", i18nKey: "originForeverCruise" },
  { img: "origins/GFX_origin_red_giant.png", i18nKey: "originRedGiant" },
  { img: "origins/GFX_origin_cosmic_dawn.png", i18nKey: "originCosmicDawn" },
  { img: "origins/GFX_origin_shroud_forged.png", i18nKey: "originShroudForged" },
  { img: "origins/GFX_origin_mindwardens.png", i18nKey: "originMindwardens" },
  { img: "origins/GFX_origin_endbringers.png", i18nKey: "originEndbringers" },
  { img: "origins/GFX_origin_evolutionary_predators.png", i18nKey: "originEvolutionaryPredators" },
  { img: "origins/GFX_origin_starlit_citadel.png", i18nKey: "originStarlitCitadel" },
  { img: "origins/GFX_origin_wilderness.png", i18nKey: "originWilderness" },
  { img: "origins/GFX_origin_treasure_hunters.png", i18nKey: "originTreasureHunters" },
  { img: "origins/GFX_origin_primal_calling.png", i18nKey: "originPrimalCalling" },
  { img: "origins/GFX_origin_storm_chasers.png", i18nKey: "originStormChasers" },
  { img: "origins/GFX_origin_cybernetic_creed.png", i18nKey: "originCyberneticCreed" },
  { img: "origins/GFX_origin_synthetic_fertility.png", i18nKey: "originSyntheticFertility" },
  { img: "origins/GFX_origin_arc_welders.png", i18nKey: "originArcWelders" },
  { img: "origins/GFX_origin_riftworld.png", i18nKey: "originRiftworld" },
  { img: "origins/GFX_origin_legendary_leader.png", i18nKey: "originLegendaryLeader" },
  { img: "origins/GFX_origin_payback.png", i18nKey: "originPayback" },
  { img: "origins/GFX_origin_broken_shackles.png", i18nKey: "originBrokenShackles" },
  { img: "origins/GFX_origin_fear_of_the_dark.png", i18nKey: "originFearOfTheDark" },
  { img: "origins/GFX_origin_overtuned.png", i18nKey: "originOvertuned" },
  { img: "origins/GFX_origin_toxic_knights.png", i18nKey: "originToxicKnights" },
  { img: "origins/GFX_origin_progenitor_hive.png", i18nKey: "originProgenitorHive" },
  { img: "origins/GFX_origin_subterranean.png", i18nKey: "originSubterranean" },
  { img: "origins/GFX_origin_star_slingshot.png", i18nKey: "originStarSlingshot" },
  { img: "origins/GFX_origin_shroudwalker_apprentice.png", i18nKey: "originShroudwalkerApprentice" },
  { img: "origins/GFX_origin_imperial_vassal.png", i18nKey: "originImperialVassal" },
  { img: "origins/GFX_origin_here_be_dragons.png", i18nKey: "originHereBeDragons" },
  { img: "origins/GFX_origin_ocean_paradise.png", i18nKey: "originOceanParadise" },
  { img: "origins/GFX_origin_necrophage.png", i18nKey: "originNecrophage" },
  { img: "origins/GFX_origin_remnants.png", i18nKey: "originRemnants" },
  { img: "origins/GFX_origin_shattered_ring.png", i18nKey: "originShatteredRing" },
  { img: "origins/GFX_origin_void_dwellers.png", i18nKey: "originVoidDwellers" },
  { img: "origins/GFX_origin_scion.png", i18nKey: "originScion" },
  { img: "origins/GFX_origin_shoulders.png", i18nKey: "originShoulders" },
  { img: "origins/GFX_origin_common_ground.png", i18nKey: "originCommonGround" },
  { img: "origins/GFX_origin_hegemon.png", i18nKey: "originHegemon" },
  { img: "origins/GFX_origin_doomsday.png", i18nKey: "originDoomsday" },
  { img: "origins/GFX_origin_calamitous.png", i18nKey: "originCalamitous" },
  { img: "origins/GFX_origin_life_seeded.png", i18nKey: "originLifeSeeded" },
  { img: "origins/GFX_origin_post_apocalyptic.png", i18nKey: "originPostApocalyptic" },
  { img: "origins/GFX_origin_clone_army.png", i18nKey: "originCloneArmy" },
  { img: "origins/GFX_origin_resource_consolidation.png", i18nKey: "originResourceConsolidation" },
  { img: "origins/GFX_origin_unplugged.png", i18nKey: "originUnplugged" },
  { img: "origins/GFX_origin_mechanist.png", i18nKey: "originMechanist" },
  { img: "origins/GFX_origin_syncretic_evolution.png", i18nKey: "originSyncreticEvolution" },
  { img: "origins/GFX_origin_tree.png", i18nKey: "originTree" },
  { img: "origins/GFX_origin_fruitful.png", i18nKey: "originFruitful" },
  { img: "origins/GFX_origin_galactic_doorstep.png", i18nKey: "originGalacticDoorstep" },
  { img: "origins/GFX_origin_lost_colony.png", i18nKey: "originLostColony" },
];

/**
 * Bingo de principios (civics). Incluye las 226 imágenes de img/civics/
 * (normales, corporativas, de mente colmena, de máquina y de máquina
 * individual). Los nombres de "i18nKey" se generaron automáticamente a
 * partir del nombre de archivo de cada civic; sus textos (en los tres
 * idiomas) están en js/i18n.js junto al resto de claves "principleXxx" —
 * revisa y ajusta ahí cualquier traducción que no te convenza, no aquí.
 *
 * Para añadir un nuevo principio en el futuro (por ejemplo, tras un DLC
 * nuevo):
 *  1. Añade su imagen en img/civics/.
 *  2. Añade una línea aquí con el mismo formato, por ejemplo:
 *     { img: "civics/48px-Civic_xxx.png", i18nKey: "principleXxx" }.
 *  3. Añade la clave "principleXxx" con su texto en los tres bloques de
 *     idioma (es/en/jp) de js/i18n.js.
 */
export const PRINCIPLE_BINGO = [
  { img: "civics/Civic_agrarian_idyll.png", i18nKey: "principleAgrarianIdyll" },
  { img: "civics/Civic_anglers.png", i18nKey: "principleAnglers" },
  { img: "civics/Civic_aristocratic_elite.png", i18nKey: "principleAristocraticElite" },
  { img: "civics/Civic_ascensionists.png", i18nKey: "principleAscensionists" },
  { img: "civics/Civic_astrometeorology.png", i18nKey: "principleAstrometeorology" },
  { img: "civics/Civic_barbaric_despoilers.png", i18nKey: "principleBarbaricDespoilers" },
  { img: "civics/Civic_beacon_of_liberty.png", i18nKey: "principleBeaconOfLiberty" },
  { img: "civics/Civic_beastmasters.png", i18nKey: "principleBeastmasters" },
  { img: "civics/Civic_brand_loyalty.png", i18nKey: "principleBrandLoyalty" },
  { img: "civics/Civic_byzantine_bureaucracy.png", i18nKey: "principleByzantineBureaucracy" },
  { img: "civics/Civic_caravan_masters.png", i18nKey: "principleCaravanMasters" },
  { img: "civics/Civic_catalytic_processing.png", i18nKey: "principleCatalyticProcessing" },
  { img: "civics/Civic_chosen.png", i18nKey: "principleChosen" },
  { img: "civics/Civic_citizen_service.png", i18nKey: "principleCitizenService" },
  { img: "civics/Civic_civil_education.png", i18nKey: "principleCivilEducation" },
  { img: "civics/Civic_corporate_anglers.png", i18nKey: "principleCorporateAnglers" },
  { img: "civics/Civic_corporate_ascensionists.png", i18nKey: "principleCorporateAscensionists" },
  { img: "civics/Civic_corporate_astrometeorology.png", i18nKey: "principleCorporateAstrometeorology" },
  { img: "civics/Civic_corporate_augmentation_bazaars.png", i18nKey: "principleCorporateAugmentationBazaars" },
  { img: "civics/Civic_corporate_beastmasters.png", i18nKey: "principleCorporateBeastmasters" },
  { img: "civics/Civic_corporate_caravan_masters.png", i18nKey: "principleCorporateCaravanMasters" },
  { img: "civics/Civic_corporate_catalytic_processing.png", i18nKey: "principleCorporateCatalyticProcessing" },
  { img: "civics/Civic_corporate_chosen.png", i18nKey: "principleCorporateChosen" },
  { img: "civics/Civic_corporate_crafters.png", i18nKey: "principleCorporateCrafters" },
  { img: "civics/Civic_corporate_crowdsourcing.png", i18nKey: "principleCorporateCrowdsourcing" },
  { img: "civics/Civic_corporate_dark_consortium.png", i18nKey: "principleCorporateDarkConsortium" },
  { img: "civics/Civic_corporate_death_cult.png", i18nKey: "principleCorporateDeathCult" },
  { img: "civics/Civic_corporate_deep_sleep.png", i18nKey: "principleCorporateDeepSleep" },
  { img: "civics/Civic_corporate_dimensional_worship.png", i18nKey: "principleCorporateDimensionalWorship" },
  { img: "civics/Civic_corporate_dominion.png", i18nKey: "principleCorporateDominion" },
  { img: "civics/Civic_corporate_entropy_drinkers.png", i18nKey: "principleCorporateEntropyDrinkers" },
  { img: "civics/Civic_corporate_flight_schools.png", i18nKey: "principleCorporateFlightSchools" },
  { img: "civics/Civic_corporate_galactic_curators.png", i18nKey: "principleCorporateGalacticCurators" },
  { img: "civics/Civic_corporate_galvanic_symbiosis.png", i18nKey: "principleCorporateGalvanicSymbiosis" },
  { img: "civics/Civic_corporate_genetic_identification.png", i18nKey: "principleCorporateGeneticIdentification" },
  { img: "civics/Civic_corporate_guided_sapience.png", i18nKey: "principleCorporateGuidedSapience" },
  { img: "civics/Civic_corporate_hedonism.png", i18nKey: "principleCorporateHedonism" },
  { img: "civics/Civic_corporate_hired_guns.png", i18nKey: "principleCorporateHiredGuns" },
  { img: "civics/Civic_corporate_hyperspace_specialty.png", i18nKey: "principleCorporateHyperspaceSpecialty" },
  { img: "civics/Civic_corporate_memory_vault.png", i18nKey: "principleCorporateMemoryVault" },
  { img: "civics/Civic_corporate_planetscapers.png", i18nKey: "principleCorporatePlanetscapers" },
  { img: "civics/Civic_corporate_relentless_industrialists.png", i18nKey: "principleCorporateRelentlessIndustrialists" },
  { img: "civics/Civic_corporate_scavengers.png", i18nKey: "principleCorporateScavengers" },
  { img: "civics/Civic_corporate_secret_societies.png", i18nKey: "principleCorporateSecretSocieties" },
  { img: "civics/Civic_corporate_sovereign_guardianship.png", i18nKey: "principleCorporateSovereignGuardianship" },
  { img: "civics/Civic_corporate_star_seekers.png", i18nKey: "principleCorporateStarSeekers" },
  { img: "civics/Civic_corporate_storm_devotion.png", i18nKey: "principleCorporateStormDevotion" },
  { img: "civics/Civic_corporate_superstitious_beliefs.png", i18nKey: "principleCorporateSuperstitiousBeliefs" },
  { img: "civics/Civic_corporate_tankbound.png", i18nKey: "principleCorporateTankbound" },
  { img: "civics/Civic_corporate_task_delegation.png", i18nKey: "principleCorporateTaskDelegation" },
  { img: "civics/Civic_corporate_toxic_baths.png", i18nKey: "principleCorporateToxicBaths" },
  { img: "civics/Civic_corporate_twisted_experimenters.png", i18nKey: "principleCorporateTwistedExperimenters" },
  { img: "civics/Civic_corporate_world_forgers.png", i18nKey: "principleCorporateWorldForgers" },
  { img: "civics/Civic_corvee_system.png", i18nKey: "principleCorveeSystem" },
  { img: "civics/Civic_crafters.png", i18nKey: "principleCrafters" },
  { img: "civics/Civic_criminal_heritage.png", i18nKey: "principleCriminalHeritage" },
  { img: "civics/Civic_crowdsourcing.png", i18nKey: "principleCrowdsourcing" },
  { img: "civics/Civic_crusader_spirit.png", i18nKey: "principleCrusaderSpirit" },
  { img: "civics/Civic_crusader_spirit_corporate.png", i18nKey: "principleCrusaderSpiritCorporate" },
  { img: "civics/Civic_cutthroat_politics.png", i18nKey: "principleCutthroatPolitics" },
  { img: "civics/Civic_dark_consortium.png", i18nKey: "principleDarkConsortium" },
  { img: "civics/Civic_death_cult.png", i18nKey: "principleDeathCult" },
  { img: "civics/Civic_deep_sleep.png", i18nKey: "principleDeepSleep" },
  { img: "civics/Civic_devouring_swarm.png", i18nKey: "principleDevouringSwarm" },
  { img: "civics/Civic_dimensional_worship.png", i18nKey: "principleDimensionalWorship" },
  { img: "civics/Civic_diplomatic_corps.png", i18nKey: "principleDiplomaticCorps" },
  { img: "civics/Civic_distinguished_admiralty.png", i18nKey: "principleDistinguishedAdmiralty" },
  { img: "civics/Civic_divided_attention.png", i18nKey: "principleDividedAttention" },
  { img: "civics/Civic_dystopian_society.png", i18nKey: "principleDystopianSociety" },
  { img: "civics/Civic_eager_explorers.png", i18nKey: "principleEagerExplorers" },
  { img: "civics/Civic_efficient_bureaucracy.png", i18nKey: "principleEfficientBureaucracy" },
  { img: "civics/Civic_empath.png", i18nKey: "principleEmpath" },
  { img: "civics/Civic_entropy_drinkers.png", i18nKey: "principleEntropyDrinkers" },
  { img: "civics/Civic_environmentalist.png", i18nKey: "principleEnvironmentalist" },
  { img: "civics/Civic_exalted_priesthood.png", i18nKey: "principleExaltedPriesthood" },
  { img: "civics/Civic_fanatic_purifiers.png", i18nKey: "principleFanaticPurifiers" },
  { img: "civics/Civic_feudal_realm.png", i18nKey: "principleFeudalRealm" },
  { img: "civics/Civic_flight_schools.png", i18nKey: "principleFlightSchools" },
  { img: "civics/Civic_franchising.png", i18nKey: "principleFranchising" },
  { img: "civics/Civic_free_haven.png", i18nKey: "principleFreeHaven" },
  { img: "civics/Civic_free_traders.png", i18nKey: "principleFreeTraders" },
  { img: "civics/Civic_functional_architecture.png", i18nKey: "principleFunctionalArchitecture" },
  { img: "civics/Civic_galactic_curators.png", i18nKey: "principleGalacticCurators" },
  { img: "civics/Civic_galactic_sovereign.png", i18nKey: "principleGalacticSovereign" },
  { img: "civics/Civic_galvanic_symbiosis.png", i18nKey: "principleGalvanicSymbiosis" },
  { img: "civics/Civic_genetic_identification.png", i18nKey: "principleGeneticIdentification" },
  { img: "civics/Civic_gospel_of_the_masses.png", i18nKey: "principleGospelOfTheMasses" },
  { img: "civics/Civic_guided_sapience.png", i18nKey: "principleGuidedSapience" },
  { img: "civics/Civic_heroic_tales.png", i18nKey: "principleHeroicTales" },
  { img: "civics/Civic_hired_guns.png", i18nKey: "principleHiredGuns" },
  { img: "civics/Civic_hive_aerospace_adaptation.png", i18nKey: "principleHiveAerospaceAdaptation" },
  { img: "civics/Civic_hive_ascensionists.png", i18nKey: "principleHiveAscensionists" },
  { img: "civics/Civic_hive_ascetic.png", i18nKey: "principleHiveAscetic" },
  { img: "civics/Civic_hive_astrometeorology.png", i18nKey: "principleHiveAstrometeorology" },
  { img: "civics/Civic_hive_beastmasters.png", i18nKey: "principleHiveBeastmasters" },
  { img: "civics/Civic_hive_bodysnatcher.png", i18nKey: "principleHiveBodysnatcher" },
  { img: "civics/Civic_hive_catalytic_processing.png", i18nKey: "principleHiveCatalyticProcessing" },
  { img: "civics/Civic_hive_chosen.png", i18nKey: "principleHiveChosen" },
  { img: "civics/Civic_hive_cordyceptic_drones.png", i18nKey: "principleHiveCordycepticDrones" },
  { img: "civics/Civic_hive_deep_sleep.png", i18nKey: "principleHiveDeepSleep" },
  { img: "civics/Civic_hive_entropy_drinkers.png", i18nKey: "principleHiveEntropyDrinkers" },
  { img: "civics/Civic_hive_familiar_face.png", i18nKey: "principleHiveFamiliarFace" },
  { img: "civics/Civic_hive_galactic_curators.png", i18nKey: "principleHiveGalacticCurators" },
  { img: "civics/Civic_hive_galvanic_symbiosis.png", i18nKey: "principleHiveGalvanicSymbiosis" },
  { img: "civics/Civic_hive_guided_sapience.png", i18nKey: "principleHiveGuidedSapience" },
  { img: "civics/Civic_hive_hyperspace_specialty.png", i18nKey: "principleHiveHyperspaceSpecialty" },
  { img: "civics/Civic_hive_idyllic_bloom.png", i18nKey: "principleHiveIdyllicBloom" },
  { img: "civics/Civic_hive_memorialist.png", i18nKey: "principleHiveMemorialist" },
  { img: "civics/Civic_hive_memory_vault.png", i18nKey: "principleHiveMemoryVault" },
  { img: "civics/Civic_hive_natural_design.png", i18nKey: "principleHiveNaturalDesign" },
  { img: "civics/Civic_hive_one_mind.png", i18nKey: "principleHiveOneMind" },
  { img: "civics/Civic_hive_planetscapers.png", i18nKey: "principleHivePlanetscapers" },
  { img: "civics/Civic_hive_pooled_knowledge.png", i18nKey: "principleHivePooledKnowledge" },
  { img: "civics/Civic_hive_scorched_earth.png", i18nKey: "principleHiveScorchedEarth" },
  { img: "civics/Civic_hive_shared_genetics.png", i18nKey: "principleHiveSharedGenetics" },
  { img: "civics/Civic_hive_sovereign_guardianship.png", i18nKey: "principleHiveSovereignGuardianship" },
  { img: "civics/Civic_hive_star_seekers.png", i18nKey: "principleHiveStarSeekers" },
  { img: "civics/Civic_hive_stargazers.png", i18nKey: "principleHiveStargazers" },
  { img: "civics/Civic_hive_superstitious_beliefs.png", i18nKey: "principleHiveSuperstitiousBeliefs" },
  { img: "civics/Civic_hive_toxic_baths.png", i18nKey: "principleHiveToxicBaths" },
  { img: "civics/Civic_hive_twisted_experimenters.png", i18nKey: "principleHiveTwistedExperimenters" },
  { img: "civics/Civic_hive_upkeep_twister.png", i18nKey: "principleHiveUpkeepTwister" },
  { img: "civics/Civic_hive_world_forgers.png", i18nKey: "principleHiveWorldForgers" },
  { img: "civics/Civic_hyperspace_specialty.png", i18nKey: "principleHyperspaceSpecialty" },
  { img: "civics/Civic_idealistic_foundation.png", i18nKey: "principleIdealisticFoundation" },
  { img: "civics/Civic_idyllic_bloom.png", i18nKey: "principleIdyllicBloom" },
  { img: "civics/Civic_imperial_cult.png", i18nKey: "principleImperialCult" },
  { img: "civics/Civic_indentured_assets.png", i18nKey: "principleIndenturedAssets" },
  { img: "civics/Civic_individual_machine_predictive_analysis.png", i18nKey: "principleIndividualMachinePredictiveAnalysis" },
  { img: "civics/Civic_individual_machine_replication.png", i18nKey: "principleIndividualMachineReplication" },
  { img: "civics/Civic_individual_machine_warbots.png", i18nKey: "principleIndividualMachineWarbots" },
  { img: "civics/Civic_inward_perfection.png", i18nKey: "principleInwardPerfection" },
  { img: "civics/Civic_machine_ascensionists.png", i18nKey: "principleMachineAscensionists" },
  { img: "civics/Civic_machine_assimilator.png", i18nKey: "principleMachineAssimilator" },
  { img: "civics/Civic_machine_astrometeorology.png", i18nKey: "principleMachineAstrometeorology" },
  { img: "civics/Civic_machine_astromining_drones.png", i18nKey: "principleMachineAstrominingDrones" },
  { img: "civics/Civic_machine_beastmasters.png", i18nKey: "principleMachineBeastmasters" },
  { img: "civics/Civic_machine_builder.png", i18nKey: "principleMachineBuilder" },
  { img: "civics/Civic_machine_built_to_last.png", i18nKey: "principleMachineBuiltToLast" },
  { img: "civics/Civic_machine_catalytic_processing.png", i18nKey: "principleMachineCatalyticProcessing" },
  { img: "civics/Civic_machine_chosen.png", i18nKey: "principleMachineChosen" },
  { img: "civics/Civic_machine_deep_sleep.png", i18nKey: "principleMachineDeepSleep" },
  { img: "civics/Civic_machine_delegated_functions.png", i18nKey: "principleMachineDelegatedFunctions" },
  { img: "civics/Civic_machine_diplomatic_protocols.png", i18nKey: "principleMachineDiplomaticProtocols" },
  { img: "civics/Civic_machine_entropy_drinkers.png", i18nKey: "principleMachineEntropyDrinkers" },
  { img: "civics/Civic_machine_exploration_protocol.png", i18nKey: "principleMachineExplorationProtocol" },
  { img: "civics/Civic_machine_factory_overclock.png", i18nKey: "principleMachineFactoryOverclock" },
  { img: "civics/Civic_machine_galactic_curators.png", i18nKey: "principleMachineGalacticCurators" },
  { img: "civics/Civic_machine_galvanic_symbiosis.png", i18nKey: "principleMachineGalvanicSymbiosis" },
  { img: "civics/Civic_machine_guided_sapience.png", i18nKey: "principleMachineGuidedSapience" },
  { img: "civics/Civic_machine_hyperspace_specialty.png", i18nKey: "principleMachineHyperspaceSpecialty" },
  { img: "civics/Civic_machine_introspective.png", i18nKey: "principleMachineIntrospective" },
  { img: "civics/Civic_machine_maintenance_protocols.png", i18nKey: "principleMachineMaintenanceProtocols" },
  { img: "civics/Civic_machine_memorialist.png", i18nKey: "principleMachineMemorialist" },
  { img: "civics/Civic_machine_memory_vault.png", i18nKey: "principleMachineMemoryVault" },
  { img: "civics/Civic_machine_obsessional_directive.png", i18nKey: "principleMachineObsessionalDirective" },
  { img: "civics/Civic_machine_ota_updates.png", i18nKey: "principleMachineOtaUpdates" },
  { img: "civics/Civic_machine_planetscapers.png", i18nKey: "principleMachinePlanetscapers" },
  { img: "civics/Civic_machine_predictive_analysis.png", i18nKey: "principleMachinePredictiveAnalysis" },
  { img: "civics/Civic_machine_replication.png", i18nKey: "principleMachineReplication" },
  { img: "civics/Civic_machine_rockbreakers.png", i18nKey: "principleMachineRockbreakers" },
  { img: "civics/Civic_machine_servitor.png", i18nKey: "principleMachineServitor" },
  { img: "civics/Civic_machine_sovereign_circuits.png", i18nKey: "principleMachineSovereignCircuits" },
  { img: "civics/Civic_machine_sovereign_guardianship.png", i18nKey: "principleMachineSovereignGuardianship" },
  { img: "civics/Civic_machine_spybots.png", i18nKey: "principleMachineSpybots" },
  { img: "civics/Civic_machine_stalwart_network.png", i18nKey: "principleMachineStalwartNetwork" },
  { img: "civics/Civic_machine_star_seekers.png", i18nKey: "principleMachineStarSeekers" },
  { img: "civics/Civic_machine_superstitious_beliefs.png", i18nKey: "principleMachineSuperstitiousBeliefs" },
  { img: "civics/Civic_machine_tactical_algorithms.png", i18nKey: "principleMachineTacticalAlgorithms" },
  { img: "civics/Civic_machine_terminator.png", i18nKey: "principleMachineTerminator" },
  { img: "civics/Civic_machine_toxic_baths.png", i18nKey: "principleMachineToxicBaths" },
  { img: "civics/Civic_machine_unitary_cohesion.png", i18nKey: "principleMachineUnitaryCohesion" },
  { img: "civics/Civic_machine_warbots.png", i18nKey: "principleMachineWarbots" },
  { img: "civics/Civic_machine_world_forgers.png", i18nKey: "principleMachineWorldForgers" },
  { img: "civics/Civic_machine_zero_waste_protocols.png", i18nKey: "principleMachineZeroWasteProtocols" },
  { img: "civics/Civic_media_conglomerate.png", i18nKey: "principleMediaConglomerate" },
  { img: "civics/Civic_memorialist.png", i18nKey: "principleMemorialist" },
  { img: "civics/Civic_memory_vault.png", i18nKey: "principleMemoryVault" },
  { img: "civics/Civic_merchant_guilds.png", i18nKey: "principleMerchantGuilds" },
  { img: "civics/Civic_meritocracy.png", i18nKey: "principleMeritocracy" },
  { img: "civics/Civic_mining_guilds.png", i18nKey: "principleMiningGuilds" },
  { img: "civics/Civic_nationalistic_zeal.png", i18nKey: "principleNationalisticZeal" },
  { img: "civics/Civic_natural_design.png", i18nKey: "principleNaturalDesign" },
  { img: "civics/Civic_natural_neural_network.png", i18nKey: "principleNaturalNeuralNetwork" },
  { img: "civics/Civic_naval_contractors.png", i18nKey: "principleNavalContractors" },
  { img: "civics/Civic_parliamentary_system.png", i18nKey: "principleParliamentarySystem" },
  { img: "civics/Civic_permanent_employment.png", i18nKey: "principlePermanentEmployment" },
  { img: "civics/Civic_philosopher_king.png", i18nKey: "principlePhilosopherKing" },
  { img: "civics/Civic_planetscapers.png", i18nKey: "principlePlanetscapers" },
  { img: "civics/Civic_pleasure_seekers.png", i18nKey: "principlePleasureSeekers" },
  { img: "civics/Civic_police_state.png", i18nKey: "principlePoliceState" },
  { img: "civics/Civic_pompous_purists.png", i18nKey: "principlePompousPurists" },
  { img: "civics/Civic_private_healthcare_corporate.png", i18nKey: "principlePrivateHealthcareCorporate" },
  { img: "civics/Civic_private_military_companies.png", i18nKey: "principlePrivateMilitaryCompanies" },
  { img: "civics/Civic_private_prospectors.png", i18nKey: "principlePrivateProspectors" },
  { img: "civics/Civic_privatized_exploration.png", i18nKey: "principlePrivatizedExploration" },
  { img: "civics/Civic_psionic_sovereign.png", i18nKey: "principlePsionicSovereign" },
  { img: "civics/Civic_public_relations_specialists.png", i18nKey: "principlePublicRelationsSpecialists" },
  { img: "civics/Civic_pyrolatry.png", i18nKey: "principlePyrolatry" },
  { img: "civics/Civic_reanimated_armies.png", i18nKey: "principleReanimatedArmies" },
  { img: "civics/Civic_relentless_industrialists.png", i18nKey: "principleRelentlessIndustrialists" },
  { img: "civics/Civic_ruthless_competition.png", i18nKey: "principleRuthlessCompetition" },
  { img: "civics/Civic_scavengers.png", i18nKey: "principleScavengers" },
  { img: "civics/Civic_scorched_earth.png", i18nKey: "principleScorchedEarth" },
  { img: "civics/Civic_secret_societies.png", i18nKey: "principleSecretSocieties" },
  { img: "civics/Civic_selective_kinship.png", i18nKey: "principleSelectiveKinship" },
  { img: "civics/Civic_shadow_council.png", i18nKey: "principleShadowCouncil" },
  { img: "civics/Civic_shared_burdens.png", i18nKey: "principleSharedBurdens" },
  { img: "civics/Civic_slaver_guilds.png", i18nKey: "principleSlaverGuilds" },
  { img: "civics/Civic_sovereign_guardianship.png", i18nKey: "principleSovereignGuardianship" },
  { img: "civics/Civic_star_seekers.png", i18nKey: "principleStarSeekers" },
  { img: "civics/Civic_storm_devotion.png", i18nKey: "principleStormDevotion" },
  { img: "civics/Civic_strength_of_legions.png", i18nKey: "principleStrengthOfLegions" },
  { img: "civics/Civic_subspace_ephapse.png", i18nKey: "principleSubspaceEphapse" },
  { img: "civics/Civic_subsumed_will.png", i18nKey: "principleSubsumedWill" },
  { img: "civics/Civic_superstitious_beliefs.png", i18nKey: "principleSuperstitiousBeliefs" },
  { img: "civics/Civic_tankbound.png", i18nKey: "principleTankbound" },
  { img: "civics/Civic_technocracy.png", i18nKey: "principleTechnocracy" },
  { img: "civics/Civic_toxic_baths.png", i18nKey: "principleToxicBaths" },
  { img: "civics/Civic_trading_posts.png", i18nKey: "principleTradingPosts" },
  { img: "civics/Civic_twisted_experimenters.png", i18nKey: "principleTwistedExperimenters" },
  { img: "civics/Civic_void_hive.png", i18nKey: "principleVoidHive" },
  { img: "civics/Civic_void_reavers.png", i18nKey: "principleVoidReavers" },
  { img: "civics/Civic_warrior_culture.png", i18nKey: "principleWarriorCulture" },
  { img: "civics/Civic_worker_coop.png", i18nKey: "principleWorkerCoop" },
  { img: "civics/Civic_world_forgers.png", i18nKey: "principleWorldForgers" },
];
